import { storage } from "./storage";

export const DEMO_ORG_ID = "00000000-demo-0000-0000-000000000000";
export const DEMO_USER_ID = "user0000-demo-0000-0000-000000000000";

export const PAYER_FAX_NUMBERS: Record<string, string> = {
  UHC: "+1-866-252-0566",
  Cigna: "+1-800-337-0255",
  Aetna: "+1-860-754-3604",
  Humana: "+1-800-457-4708",
};

export async function ensureDemoOrg() {
  const existingOrg = storage.getOrganization(DEMO_ORG_ID);
  if (existingOrg) {
    console.log("[Seed] Demo organization already exists. Skipping seed.");
    return { status: "already_seeded" };
  }

  const today = new Date().toISOString().split("T")[0];
  console.log("[Seed] Creating demo organization and data...");

  storage.insertOrganization({
    id: DEMO_ORG_ID,
    name: "MD Anderson Cancer Center (Demo)",
    slug: "demo",
    logoUrl: null,
    address: "1515 Holcombe Blvd",
    city: "Houston",
    state: "TX",
    zip: "77030",
    npi: "1234567890",
    phone: "+1-713-792-2121",
    outboundFax: "+1-713-792-0000",
    signingPhysician: "Dr. Sarah Miller",
    signingTitle: "Attending Oncologist",
    plan: "enterprise",
    isDemo: true,
  });

  storage.insertUser({
    id: DEMO_USER_ID,
    organizationId: DEMO_ORG_ID,
    role: "admin",
    fullName: "Dr. James Smith",
    title: "MD, Oncology",
    email: "dr.smith@mdanderson.org",
  });

  // ─── DRUGS ───────────────────────────────────────────────────────────────────
  const drugData = [
    { id: "enhertu", genericName: "trastuzumab deruxtecan", brandName: "Enhertu", cancerType: "breast", indication: "Metastatic HER2-low or HER2-positive breast cancer", lineOfTherapy: "2L", biomarkerProfile: JSON.stringify({ HER2: "low or positive" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for unresectable or metastatic HER2-positive breast cancer (Aug 2019) and HER2-low (Aug 2022) after prior chemotherapy.", fdaLabelReference: "NDA 761139", drugClass: "ADC" },
    { id: "trodelvy", genericName: "sacituzumab govitecan", brandName: "Trodelvy", cancerType: "breast", indication: "Metastatic triple-negative breast cancer (TNBC)", lineOfTherapy: "2L", biomarkerProfile: JSON.stringify({ TNBC: "positive", Trop2: "expressed" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for unresectable locally advanced or metastatic TNBC (Apr 2021) after prior therapies.", fdaLabelReference: "BLA 761115", drugClass: "ADC" },
    { id: "verzenio", genericName: "abemaciclib", brandName: "Verzenio", cancerType: "breast", indication: "HR+/HER2- early or advanced breast cancer", lineOfTherapy: "1L", biomarkerProfile: JSON.stringify({ HR: "positive", HER2: "negative", Ki67: "high" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for HR+/HER2- early breast cancer with Ki67 >=20% (Oct 2021) and advanced disease.", fdaLabelReference: "NDA 208716", drugClass: "targeted" },
    { id: "tagrisso", genericName: "osimertinib", brandName: "Tagrisso", cancerType: "lung_nsclc", indication: "EGFR-mutant NSCLC (ex19del or L858R)", lineOfTherapy: "1L", biomarkerProfile: JSON.stringify({ EGFR: "ex19del or L858R" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for first-line EGFR ex19del or L858R NSCLC (Apr 2018). FLAURA trial demonstrated superior OS vs first-gen TKIs.", fdaLabelReference: "NDA 208065", drugClass: "targeted" },
    { id: "keytruda-nsclc", genericName: "pembrolizumab", brandName: "Keytruda (NSCLC)", cancerType: "lung_nsclc", indication: "PD-L1 >=1% NSCLC without EGFR/ALK", lineOfTherapy: "1L", biomarkerProfile: JSON.stringify({ PDL1: ">=1%", EGFR: "negative", ALK: "negative" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for metastatic NSCLC with PD-L1 >=1% without EGFR or ALK alterations (Oct 2016). KEYNOTE-024 demonstrated superior PFS.", fdaLabelReference: "BLA 125514", drugClass: "checkpoint_inhibitor" },
    { id: "alecensa", genericName: "alectinib", brandName: "Alecensa", cancerType: "lung_nsclc", indication: "ALK-positive metastatic NSCLC", lineOfTherapy: "1L", biomarkerProfile: JSON.stringify({ ALK: "positive rearrangement" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for ALK-positive metastatic NSCLC as first-line (Nov 2017). ALEX trial showed superior PFS vs crizotinib.", fdaLabelReference: "NDA 208434", drugClass: "targeted" },
    { id: "temodar", genericName: "temozolomide", brandName: "Temodar", cancerType: "glioblastoma", indication: "Newly diagnosed GBM with concurrent radiotherapy", lineOfTherapy: "1L", biomarkerProfile: JSON.stringify({ MGMT: "any", IDH: "wildtype" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for newly diagnosed GBM concomitant with radiotherapy then as maintenance (Mar 2005).", fdaLabelReference: "NDA 021029", drugClass: "chemo" },
    { id: "optune", genericName: "tumor treating fields", brandName: "Optune", cancerType: "glioblastoma", indication: "Newly diagnosed GBM after surgery and chemoradiation", lineOfTherapy: "1L", biomarkerProfile: JSON.stringify({ IDH: "wildtype" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved (Oct 2015) for newly diagnosed GBM as adjunct to TMZ maintenance. EF-14 trial extended median OS.", fdaLabelReference: "PMA P140003", drugClass: "targeted" },
    { id: "vorasidenib", genericName: "vorasidenib", brandName: "Voranigo", cancerType: "glioblastoma", indication: "Grade 2 IDH-mutant glioma after surgery", lineOfTherapy: "1L", biomarkerProfile: JSON.stringify({ IDH1: "mutated", IDH2: "mutated" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved Aug 2024 for adults with residual or recurrent grade 2 IDH-mutant glioma. INDIGO trial showed 61% PFS improvement.", fdaLabelReference: "NDA 218108", drugClass: "targeted" },
    { id: "enzalutamide", genericName: "enzalutamide", brandName: "Xtandi", cancerType: "prostate", indication: "Metastatic castration-resistant prostate cancer", lineOfTherapy: "1L", biomarkerProfile: JSON.stringify({ AR: "positive", CRPC: "yes" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for metastatic CRPC (Aug 2012) and non-metastatic CRPC (Jul 2018).", fdaLabelReference: "NDA 203415", drugClass: "targeted" },
    // Rheumatology
    { id: "adalimumab", genericName: "adalimumab", brandName: "Humira", cancerType: "rheumatology", indication: "Moderate-to-severe rheumatoid arthritis", lineOfTherapy: "2L", biomarkerProfile: JSON.stringify({ RF: "positive or negative", anti_CCP: "any" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for moderate-to-severe RA (Dec 2002). ACR Category A recommendation for biologic DMARD after methotrexate failure.", fdaLabelReference: "BLA 125057", drugClass: "biologic_DMARD" },
    { id: "secukinumab", genericName: "secukinumab", brandName: "Cosentyx", cancerType: "rheumatology", indication: "Active psoriatic arthritis or ankylosing spondylitis", lineOfTherapy: "2L", biomarkerProfile: JSON.stringify({ HLA_B27: "any", CRP: "elevated" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for psoriatic arthritis (Jan 2016) and ankylosing spondylitis (Jan 2016). ACR Category A recommendation.", fdaLabelReference: "BLA 125504", drugClass: "biologic_DMARD" },
    { id: "upadacitinib", genericName: "upadacitinib", brandName: "Rinvoq", cancerType: "rheumatology", indication: "Moderate-to-severe RA after methotrexate failure", lineOfTherapy: "2L", biomarkerProfile: JSON.stringify({ JAK: "inhibitor_target", RF: "any" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for moderate-to-severe RA (Aug 2019). SELECT-COMPARE trial showed superior ACR50 vs adalimumab.", fdaLabelReference: "NDA 211675", drugClass: "JAK_inhibitor" },
    // Neurology
    { id: "ocrelizumab", genericName: "ocrelizumab", brandName: "Ocrevus", cancerType: "neurology", indication: "Relapsing or primary progressive multiple sclerosis", lineOfTherapy: "1L", biomarkerProfile: JSON.stringify({ MS_type: "RRMS or PPMS", CD20: "positive" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for relapsing MS and primary progressive MS (Mar 2017). ORATORIO trial showed 24% reduction in disability progression.", fdaLabelReference: "BLA 761053", drugClass: "anti_CD20" },
    { id: "natalizumab", genericName: "natalizumab", brandName: "Tysabri", cancerType: "neurology", indication: "Relapsing forms of multiple sclerosis", lineOfTherapy: "2L", biomarkerProfile: JSON.stringify({ MS_type: "RRMS", JCV_antibody: "negative preferred" }), fdaApprovalStatus: "approved", fdaLabelSummary: "FDA approved for relapsing MS (Nov 2004). AFFIRM trial showed 68% reduction in annualized relapse rate.", fdaLabelReference: "BLA 125104", drugClass: "anti_integrin" },
  ];

  drugData.forEach(d => storage.upsertDrug(d));

  // ─── NCCN GUIDELINES ─────────────────────────────────────────────────────────
  const nccnData = [
    { nccnId: "NCCN-BREAST-2L-HER2LOW", guidelineVersion: "Breast Cancer v2.2026", cancerType: "breast", indication: "Metastatic HER2-low breast cancer", biomarkerProfile: '{"HER2":"low","HR":"positive or negative"}', lineOfTherapy: "2L", drugId: "enhertu", nccnCategory: "1", recommendationType: "preferred", pageReference: "BRE-M p.10", fullCitationText: "NCCN Category 1: Trastuzumab deruxtecan is the preferred regimen for HER2-low metastatic breast cancer in the second-line setting. DESTINY-Breast04 demonstrated superior PFS and OS.", lastUpdated: today },
    { nccnId: "NCCN-BREAST-2L-TNBC", guidelineVersion: "Breast Cancer v2.2026", cancerType: "breast", indication: "Metastatic TNBC", biomarkerProfile: '{"TNBC":"positive","Trop2":"expressed"}', lineOfTherapy: "2L", drugId: "trodelvy", nccnCategory: "1", recommendationType: "preferred", pageReference: "BRE-M p.14", fullCitationText: "NCCN Category 1: Sacituzumab govitecan is the preferred regimen for metastatic TNBC in the second-line setting. ASCENT trial demonstrated superior OS.", lastUpdated: today },
    { nccnId: "NCCN-BREAST-1L-HR-HER2NEG", guidelineVersion: "Breast Cancer v2.2026", cancerType: "breast", indication: "HR+/HER2- early breast cancer high recurrence risk", biomarkerProfile: '{"HR":"positive","HER2":"negative","Ki67":">=20%"}', lineOfTherapy: "1L", drugId: "verzenio", nccnCategory: "1", recommendationType: "preferred", pageReference: "BRE-A p.5", fullCitationText: "NCCN Category 1: Abemaciclib plus endocrine therapy for HR+/HER2- early breast cancer with high recurrence risk (Ki67 >=20% or node-positive).", lastUpdated: today },
    { nccnId: "NCCN-LUNG-1L-EGFR", guidelineVersion: "NSCLC v4.2026", cancerType: "lung_nsclc", indication: "EGFR-mutant NSCLC first-line", biomarkerProfile: '{"EGFR":"ex19del or L858R"}', lineOfTherapy: "1L", drugId: "tagrisso", nccnCategory: "1", recommendationType: "preferred", pageReference: "NSCLC-18 p.9", fullCitationText: "NCCN Category 1: Osimertinib is the preferred first-line therapy for EGFR exon 19 deletion or L858R substitution NSCLC. FLAURA trial demonstrated superior OS vs first-gen TKIs.", lastUpdated: today },
    { nccnId: "NCCN-LUNG-1L-PDL1", guidelineVersion: "NSCLC v4.2026", cancerType: "lung_nsclc", indication: "PD-L1 >=1% NSCLC no driver mutation", biomarkerProfile: '{"PDL1":">=1%","EGFR":"negative","ALK":"negative"}', lineOfTherapy: "1L", drugId: "keytruda-nsclc", nccnCategory: "1", recommendationType: "preferred", pageReference: "NSCLC-16 p.8", fullCitationText: "NCCN Category 1: Pembrolizumab monotherapy or combination chemoimmunotherapy for PD-L1 >=1% NSCLC. KEYNOTE-024 demonstrated superior PFS for PD-L1 >=50%.", lastUpdated: today },
    { nccnId: "NCCN-LUNG-1L-ALK", guidelineVersion: "NSCLC v4.2026", cancerType: "lung_nsclc", indication: "ALK-positive metastatic NSCLC", biomarkerProfile: '{"ALK":"positive"}', lineOfTherapy: "1L", drugId: "alecensa", nccnCategory: "1", recommendationType: "preferred", pageReference: "NSCLC-20 p.11", fullCitationText: "NCCN Category 1: Alectinib is the preferred first-line therapy for ALK-positive metastatic NSCLC. ALEX trial showed superior PFS vs crizotinib.", lastUpdated: today },
    { nccnId: "NCCN-BRAIN-1L-GBM", guidelineVersion: "CNS Cancers v2.2026", cancerType: "glioblastoma", indication: "Newly diagnosed GBM", biomarkerProfile: '{"IDH":"wildtype","MGMT":"any"}', lineOfTherapy: "1L", drugId: "temodar", nccnCategory: "1", recommendationType: "preferred", pageReference: "GBM-2 p.4", fullCitationText: "NCCN Category 1: Temozolomide concurrent with radiotherapy followed by maintenance TMZ for newly diagnosed GBM.", lastUpdated: today },
    { nccnId: "NCCN-BRAIN-1L-TTF", guidelineVersion: "CNS Cancers v2.2026", cancerType: "glioblastoma", indication: "Newly diagnosed GBM post-chemoradiation", biomarkerProfile: '{"IDH":"wildtype"}', lineOfTherapy: "1L", drugId: "optune", nccnCategory: "1", recommendationType: "preferred", pageReference: "GBM-3 p.5", fullCitationText: "NCCN Category 1: Tumor treating fields (TTF) with temozolomide maintenance for newly diagnosed GBM. EF-14 trial extended median OS to 20.9 months.", lastUpdated: today },
    { nccnId: "NCCN-BRAIN-1L-GLIOMA-IDH", guidelineVersion: "CNS Cancers v2.2026", cancerType: "glioblastoma", indication: "Grade 2 IDH-mutant glioma post-surgery", biomarkerProfile: '{"IDH1":"mutated","IDH2":"mutated"}', lineOfTherapy: "1L", drugId: "vorasidenib", nccnCategory: "1", recommendationType: "preferred", pageReference: "GLIO-2 p.6", fullCitationText: "NCCN Category 1: Vorasidenib for residual or recurrent grade 2 IDH-mutant glioma. INDIGO trial showed 61% reduction in risk of progression.", lastUpdated: today },
    { nccnId: "NCCN-PROSTATE-1L-CRPC", guidelineVersion: "Prostate Cancer v2.2026", cancerType: "prostate", indication: "Metastatic CRPC", biomarkerProfile: '{"AR":"positive","CRPC":"yes"}', lineOfTherapy: "1L", drugId: "enzalutamide", nccnCategory: "1", recommendationType: "preferred", pageReference: "PROS-G p.7", fullCitationText: "NCCN Category 1: Enzalutamide for metastatic castration-resistant prostate cancer. PREVAIL trial demonstrated superior OS.", lastUpdated: today },
    // Rheumatology guidelines (ACR equivalent)
    { nccnId: "ACR-RA-2L-BIOLOGIC", guidelineVersion: "ACR RA Guidelines 2024", cancerType: "rheumatology", indication: "Moderate-to-severe RA after methotrexate failure", biomarkerProfile: '{"RF":"any","anti_CCP":"any"}', lineOfTherapy: "2L", drugId: "adalimumab", nccnCategory: "1", recommendationType: "preferred", pageReference: "ACR 2024 p.12", fullCitationText: "ACR Category A (strong recommendation): TNF inhibitor (adalimumab) as preferred biologic DMARD after conventional DMARD failure in moderate-to-severe RA.", lastUpdated: today },
    { nccnId: "ACR-PsA-2L-IL17", guidelineVersion: "ACR PsA Guidelines 2024", cancerType: "rheumatology", indication: "Active psoriatic arthritis after DMARD failure", biomarkerProfile: '{"HLA_B27":"any"}', lineOfTherapy: "2L", drugId: "secukinumab", nccnCategory: "1", recommendationType: "preferred", pageReference: "ACR 2024 p.18", fullCitationText: "ACR Category A: IL-17A inhibitor (secukinumab) as preferred biologic for psoriatic arthritis with predominant skin involvement.", lastUpdated: today },
    { nccnId: "ACR-RA-2L-JAK", guidelineVersion: "ACR RA Guidelines 2024", cancerType: "rheumatology", indication: "Moderate-to-severe RA after biologic failure", biomarkerProfile: '{"JAK":"inhibitor_target"}', lineOfTherapy: "2L", drugId: "upadacitinib", nccnCategory: "1", recommendationType: "preferred", pageReference: "ACR 2024 p.15", fullCitationText: "ACR Category A: JAK inhibitor (upadacitinib) as preferred option after biologic DMARD failure in moderate-to-severe RA.", lastUpdated: today },
    // Neurology guidelines (AAN equivalent)
    { nccnId: "AAN-MS-1L-ANTI-CD20", guidelineVersion: "AAN MS Guidelines 2024", cancerType: "neurology", indication: "Relapsing or primary progressive MS", biomarkerProfile: '{"MS_type":"RRMS or PPMS"}', lineOfTherapy: "1L", drugId: "ocrelizumab", nccnCategory: "1", recommendationType: "preferred", pageReference: "AAN 2024 p.8", fullCitationText: "AAN Level A (established as effective): Ocrelizumab for relapsing MS and primary progressive MS. ORATORIO trial demonstrated 24% reduction in disability progression.", lastUpdated: today },
    { nccnId: "AAN-MS-2L-NATALIZUMAB", guidelineVersion: "AAN MS Guidelines 2024", cancerType: "neurology", indication: "Highly active relapsing MS", biomarkerProfile: '{"MS_type":"RRMS","JCV_antibody":"negative preferred"}', lineOfTherapy: "2L", drugId: "natalizumab", nccnCategory: "1", recommendationType: "preferred", pageReference: "AAN 2024 p.11", fullCitationText: "AAN Level A: Natalizumab for highly active relapsing MS. AFFIRM trial showed 68% reduction in annualized relapse rate.", lastUpdated: today },
  ];

  nccnData.forEach(n => storage.insertNccn(n));

  // ─── PAYER POLICIES ──────────────────────────────────────────────────────────
  const policies = [
    { payerId: "UHC", policyId: "MP-ONC-1234", policyVersion: "2025-Q4", drugId: "enhertu", cancerType: "breast", indication: "Metastatic breast cancer", biomarkerConstraints: "HER2-positive only (IHC 3+ or ISH+); does not cover HER2-low", stepTherapyRequirements: "trastuzumab, pertuzumab", experimentalInvestigationalFlag: false, experimentalRationale: null, priorAuthRequired: true, notMedicallyNecessaryLanguage: "Not covered for HER2-low (IHC 1+, IHC 2+/ISH-) as clinical benefit not established per plan criteria", coverageCriteriaText: "Coverage requires HER2-positive disease confirmed by IHC 3+ or ISH+. HER2-low does not meet criteria under this policy.", policySourceUrl: "https://www.uhcprovider.com/policies", policyEffectiveDate: "2025-01-01", lastValidated: today },
    { payerId: "UHC", policyId: "MP-ONC-2891", policyVersion: "2025-Q4", drugId: "optune", cancerType: "glioblastoma", indication: "GBM", biomarkerConstraints: null, stepTherapyRequirements: "temozolomide, radiation", experimentalInvestigationalFlag: true, experimentalRationale: "Classified as experimental/investigational; insufficient long-term survival data per UHC medical technology assessment", priorAuthRequired: true, notMedicallyNecessaryLanguage: "Tumor Treating Fields device classified as experimental; coverage denied pending further clinical evidence", coverageCriteriaText: "TTF devices are not covered under this policy as they are considered experimental and investigational per UHC technology assessment committee.", policySourceUrl: "https://www.uhcprovider.com/policies", policyEffectiveDate: "2025-01-01", lastValidated: today },
    { payerId: "UHC", policyId: "MP-ONC-3301", policyVersion: "2025-Q4", drugId: "vorasidenib", cancerType: "glioblastoma", indication: "IDH-mutant glioma", biomarkerConstraints: "IDH1/IDH2 mutation required", stepTherapyRequirements: "temozolomide", experimentalInvestigationalFlag: true, experimentalRationale: "Limited long-term outcome data; FDA approval recent (2024); classified experimental pending broader evidence", priorAuthRequired: true, notMedicallyNecessaryLanguage: null, coverageCriteriaText: "Vorasidenib classified as experimental/investigational for glioma. Requires Medical Director review.", policySourceUrl: "https://www.uhcprovider.com/policies", policyEffectiveDate: "2025-01-01", lastValidated: today },
    { payerId: "UHC", policyId: "MP-ONC-4102", policyVersion: "2025-Q4", drugId: "tagrisso", cancerType: "lung_nsclc", indication: "EGFR-mutant NSCLC", biomarkerConstraints: "EGFR ex19del or L858R required", stepTherapyRequirements: "erlotinib or gefitinib for first-line", experimentalInvestigationalFlag: false, experimentalRationale: null, priorAuthRequired: true, notMedicallyNecessaryLanguage: null, coverageCriteriaText: "Prior authorization required. First-line coverage requires trial of first-generation EGFR TKI (erlotinib/gefitinib) unless T790M+ at diagnosis.", policySourceUrl: "https://www.uhcprovider.com/policies", policyEffectiveDate: "2025-01-01", lastValidated: today },
    { payerId: "Cigna", policyId: "CPG-ONC-0887", policyVersion: "2025-11", drugId: "trodelvy", cancerType: "breast", indication: "Metastatic TNBC", biomarkerConstraints: "Must have PD-L1 testing; prior checkpoint inhibitor required for PD-L1+ disease", stepTherapyRequirements: "atezolizumab or pembrolizumab, carboplatin, gemcitabine", experimentalInvestigationalFlag: false, priorAuthRequired: true, notMedicallyNecessaryLanguage: "Not medically necessary unless >=2 prior lines including checkpoint inhibitor for PD-L1+ disease", coverageCriteriaText: "For metastatic TNBC: covered after >=2 prior cytotoxic regimens. PD-L1+ patients must have received checkpoint inhibitor.", policySourceUrl: "https://cignapolicies.com/oncology", policyEffectiveDate: "2025-11-01", lastValidated: today },
    { payerId: "Cigna", policyId: "CPG-ONC-3315", policyVersion: "2025-11", drugId: "keytruda-nsclc", cancerType: "lung_nsclc", indication: "NSCLC PD-L1 positive", biomarkerConstraints: "PD-L1 >=50% for monotherapy; >=1% only with chemotherapy combination", stepTherapyRequirements: "carboplatin-based doublet chemotherapy for PD-L1 1-49%", experimentalInvestigationalFlag: false, priorAuthRequired: true, notMedicallyNecessaryLanguage: "Monotherapy not covered for PD-L1 1-49%; combination required", coverageCriteriaText: "Pembrolizumab monotherapy covered only for PD-L1 >=50%. For PD-L1 1-49%, must combine with platinum-doublet chemotherapy.", policySourceUrl: "https://cignapolicies.com/oncology", policyEffectiveDate: "2025-11-01", lastValidated: today },
    { payerId: "Aetna", policyId: "CPB-0600", policyVersion: "2026-01", drugId: "verzenio", cancerType: "breast", indication: "HR+/HER2- breast cancer", biomarkerConstraints: "Node-positive or Ki67 >=20%; high genomic risk score", stepTherapyRequirements: "letrozole or anastrozole (3 months minimum)", experimentalInvestigationalFlag: false, priorAuthRequired: true, notMedicallyNecessaryLanguage: "Not medically necessary for node-negative low-risk disease", coverageCriteriaText: "Abemaciclib covered for HR+/HER2- high-risk early breast cancer. Requires node-positive disease or Ki67 >=20% with genomic high-risk score.", policySourceUrl: "https://www.aetna.com/cpb/medical/data/600_699/0600.html", policyEffectiveDate: "2026-01-01", lastValidated: today },
    { payerId: "Aetna", policyId: "CPB-0910", policyVersion: "2026-01", drugId: "alecensa", cancerType: "lung_nsclc", indication: "ALK-positive NSCLC", biomarkerConstraints: "ALK rearrangement confirmed by FISH or IHC", stepTherapyRequirements: "crizotinib (prior ALK inhibitor)", experimentalInvestigationalFlag: false, priorAuthRequired: true, notMedicallyNecessaryLanguage: "Not medically necessary as first-line without crizotinib trial", coverageCriteriaText: "Alectinib for ALK-positive NSCLC: covered as second-line after crizotinib failure. First-line requires prior authorization and crizotinib contraindication documentation.", policySourceUrl: "https://www.aetna.com/cpb/medical/data/900_999/0910.html", policyEffectiveDate: "2026-01-01", lastValidated: today },
    { payerId: "Humana", policyId: "HUM-ONC-441", policyVersion: "2025-10", drugId: "enhertu", cancerType: "breast", indication: "Metastatic breast cancer HER2+", biomarkerConstraints: "HER2 3+ by IHC or ISH amplified; HER2-low indication not covered", stepTherapyRequirements: "trastuzumab + pertuzumab + docetaxel, then TDM1", experimentalInvestigationalFlag: false, priorAuthRequired: true, notMedicallyNecessaryLanguage: "Denied for HER2-low: classified as not medically necessary; insufficient peer-reviewed evidence beyond TDM1", coverageCriteriaText: "Prior authorization required. Must have progressed on trastuzumab + pertuzumab AND TDM1. HER2-low indication requires expanded Medical Director review.", policySourceUrl: "https://humana.com/providers/drug-policies", policyEffectiveDate: "2025-10-01", lastValidated: today },
    { payerId: "Humana", policyId: "HUM-ONC-603", policyVersion: "2025-10", drugId: "tagrisso", cancerType: "lung_nsclc", indication: "EGFR-mutant NSCLC", biomarkerConstraints: "EGFR ex19del or L858R required", stepTherapyRequirements: "gefitinib or erlotinib (first-generation TKI, 30-day minimum)", experimentalInvestigationalFlag: false, priorAuthRequired: true, notMedicallyNecessaryLanguage: "Not medically necessary as first-line for patients who have not trialed first-generation EGFR TKI unless T790M+ at diagnosis", coverageCriteriaText: "Osimertinib covered as first-line only with documented contraindication or intolerance to first-generation TKI, OR T790M+ at diagnosis.", policySourceUrl: "https://humana.com/providers/drug-policies", policyEffectiveDate: "2025-10-01", lastValidated: today },
    // Rheumatology payer policies
    { payerId: "UHC", policyId: "MP-RHEUM-1101", policyVersion: "2025-Q4", drugId: "adalimumab", cancerType: "rheumatology", indication: "Moderate-to-severe RA", biomarkerConstraints: null, stepTherapyRequirements: "methotrexate (3 months minimum), hydroxychloroquine", experimentalInvestigationalFlag: false, priorAuthRequired: true, notMedicallyNecessaryLanguage: "Not medically necessary without documented failure of 2 conventional DMARDs", coverageCriteriaText: "Adalimumab covered for moderate-to-severe RA after failure of methotrexate AND one additional conventional DMARD.", policySourceUrl: "https://www.uhcprovider.com/policies", policyEffectiveDate: "2025-01-01", lastValidated: today },
    { payerId: "Cigna", policyId: "CPG-RHEUM-0445", policyVersion: "2025-11", drugId: "upadacitinib", cancerType: "rheumatology", indication: "Moderate-to-severe RA", biomarkerConstraints: null, stepTherapyRequirements: "methotrexate, TNF inhibitor (adalimumab or etanercept)", experimentalInvestigationalFlag: false, priorAuthRequired: true, notMedicallyNecessaryLanguage: "Not medically necessary without prior TNF inhibitor failure due to cardiovascular risk profile of JAK inhibitors", coverageCriteriaText: "Upadacitinib covered only after failure of TNF inhibitor. Black box warning for cardiovascular events requires prior TNF inhibitor trial.", policySourceUrl: "https://cignapolicies.com/rheumatology", policyEffectiveDate: "2025-11-01", lastValidated: today },
    // Neurology payer policies
    { payerId: "UHC", policyId: "MP-NEURO-2201", policyVersion: "2025-Q4", drugId: "ocrelizumab", cancerType: "neurology", indication: "Relapsing or primary progressive MS", biomarkerConstraints: "MRI-confirmed MS lesions required", stepTherapyRequirements: "interferon beta or glatiramer acetate (6 months minimum)", experimentalInvestigationalFlag: false, priorAuthRequired: true, notMedicallyNecessaryLanguage: "Not medically necessary as first-line without prior platform therapy failure", coverageCriteriaText: "Ocrelizumab covered for relapsing MS after failure of interferon beta or glatiramer acetate. PPMS covered without step therapy requirement.", policySourceUrl: "https://www.uhcprovider.com/policies", policyEffectiveDate: "2025-01-01", lastValidated: today },
    { payerId: "Aetna", policyId: "CPB-NEURO-0330", policyVersion: "2026-01", drugId: "natalizumab", cancerType: "neurology", indication: "Highly active relapsing MS", biomarkerConstraints: "JCV antibody testing required; positive JCV requires risk-benefit discussion", stepTherapyRequirements: "interferon beta, glatiramer acetate, or dimethyl fumarate", experimentalInvestigationalFlag: false, priorAuthRequired: true, notMedicallyNecessaryLanguage: "Not medically necessary without prior failure of 2 platform therapies", coverageCriteriaText: "Natalizumab covered for highly active RRMS after failure of 2 platform therapies. JCV antibody index monitoring required every 6 months.", policySourceUrl: "https://www.aetna.com/cpb/medical/data/300_399/0330.html", policyEffectiveDate: "2026-01-01", lastValidated: today },
  ];

  policies.forEach(p => storage.insertPayerPolicy(p));

  // ─── GROUND TRUTH ────────────────────────────────────────────────────────────
  const gtRows = [
    { groundTruthRowId: "GT-UHC-OPTUNE-1L-GBM", drugId: "optune", cancerType: "glioblastoma", indication: "Newly diagnosed GBM", biomarkerProfile: '{"IDH":"wildtype"}', lineOfTherapy: "1L", nccnId: "NCCN-BRAIN-1L-TTF", nccnCategory: "1", payerId: "UHC", policyId: "MP-ONC-2891", denialRationaleType: "experimental", denialTextSnippet: "TTF devices are not covered under this policy as they are considered experimental and investigational per UHC technology assessment committee.", conflictType: "A", conflictDescription: "NCCN Category 1 drug labeled experimental by UHC. Optune demonstrated OS benefit in EF-14 phase III trial (FDA approved 2015). UHC classification contradicts highest-level clinical evidence.", cmsBehaviorFlags: '{"prior_auth_flag":true,"pattern":"PA required across all UHC plan IDs in NY, NJ, CA"}', legalExposureTags: '["contradicts NCCN Cat 1","FDA approved","pattern denial","bad-faith classification"]', severity: "high", lastValidatedTimestamp: today },
    { groundTruthRowId: "GT-UHC-VORASIDENIB-1L-GBM", drugId: "vorasidenib", cancerType: "glioblastoma", indication: "Grade 2 IDH-mutant glioma", biomarkerProfile: '{"IDH1":"mutated"}', lineOfTherapy: "1L", nccnId: "NCCN-BRAIN-1L-GLIOMA-IDH", nccnCategory: "1", payerId: "UHC", policyId: "MP-ONC-3301", denialRationaleType: "experimental", denialTextSnippet: "Vorasidenib classified as experimental/investigational for glioma. Requires Medical Director review.", conflictType: "A", conflictDescription: "NCCN Category 1 (added 2025) but UHC classifies as experimental. FDA approved Aug 2024 based on INDIGO phase 3 trial showing 61% PFS improvement.", cmsBehaviorFlags: '{"prior_auth_flag":true,"allowed_amount_suspicious":true}', legalExposureTags: '["contradicts NCCN Cat 1","FDA approved 2024","systematic barrier","recent approval delay pattern"]', severity: "high", lastValidatedTimestamp: today },
    { groundTruthRowId: "GT-UHC-ENHERTU-2L-BREAST-HER2LOW", drugId: "enhertu", cancerType: "breast", indication: "Metastatic HER2-low breast cancer", biomarkerProfile: '{"HER2":"low","HR":"positive"}', lineOfTherapy: "2L", nccnId: "NCCN-BREAST-2L-HER2LOW", nccnCategory: "1", payerId: "UHC", policyId: "MP-ONC-1234", denialRationaleType: "not_medically_necessary", denialTextSnippet: "Not covered for HER2-low (IHC 1+, IHC 2+/ISH-) as clinical benefit not established per plan criteria", conflictType: "B", conflictDescription: "FDA approved Aug 2022 specifically for HER2-low. NCCN Category 1 recommendation. UHC policy only recognizes HER2-positive (3+ or ISH+), directly contradicting the FDA indication and NCCN guideline for HER2-low.", cmsBehaviorFlags: '{"prior_auth_flag":true,"allowed_amount":0.00,"pattern":"zero allowed amounts observed across UHC plans in NY"}', legalExposureTags: '["contradicts NCCN Cat 1","FDA HER2-low indication","zero allowed amount CMS data","bad-faith NMN"]', severity: "high", lastValidatedTimestamp: today },
    { groundTruthRowId: "GT-HUMANA-ENHERTU-2L-BREAST", drugId: "enhertu", cancerType: "breast", indication: "Metastatic HER2-low breast cancer", biomarkerProfile: '{"HER2":"low"}', lineOfTherapy: "2L", nccnId: "NCCN-BREAST-2L-HER2LOW", nccnCategory: "1", payerId: "Humana", policyId: "HUM-ONC-441", denialRationaleType: "not_medically_necessary", denialTextSnippet: "Denied for HER2-low: classified as not medically necessary; insufficient peer-reviewed evidence beyond TDM1", conflictType: "B", conflictDescription: "Humana NMN denial directly contradicts FDA approval for HER2-low indication and NCCN Category 1 recommendation in the same clinical scenario.", cmsBehaviorFlags: '{"prior_auth_flag":true}', legalExposureTags: '["NMN contradicts FDA label","contradicts NCCN Cat 1","cross-payer denial pattern"]', severity: "high", lastValidatedTimestamp: today },
    { groundTruthRowId: "GT-UHC-TAGRISSO-1L-LUNG", drugId: "tagrisso", cancerType: "lung_nsclc", indication: "EGFR-mutant NSCLC first-line", biomarkerProfile: '{"EGFR":"ex19del or L858R"}', lineOfTherapy: "1L", nccnId: "NCCN-LUNG-1L-EGFR", nccnCategory: "1", payerId: "UHC", policyId: "MP-ONC-4102", denialRationaleType: "step_therapy", denialTextSnippet: "First-line coverage requires trial of first-generation EGFR TKI (erlotinib/gefitinib) unless T790M+ at diagnosis.", conflictType: "C", conflictDescription: "UHC step therapy requires erlotinib/gefitinib before osimertinib. NCCN Category 1 designates osimertinib as preferred FIRST-LINE. FLAURA trial showed superior OS with osimertinib vs first-gen TKIs.", cmsBehaviorFlags: '{"prior_auth_flag":true,"step_therapy_denials":"high frequency in NY/NJ plans"}', legalExposureTags: '["step therapy contradicts NCCN sequence","forces inferior therapy","FLAURA OS data ignored","ERISA 502"]', severity: "high", lastValidatedTimestamp: today },
    { groundTruthRowId: "GT-HUMANA-TAGRISSO-1L-LUNG", drugId: "tagrisso", cancerType: "lung_nsclc", indication: "EGFR-mutant NSCLC first-line", biomarkerProfile: '{"EGFR":"ex19del or L858R"}', lineOfTherapy: "1L", nccnId: "NCCN-LUNG-1L-EGFR", nccnCategory: "1", payerId: "Humana", policyId: "HUM-ONC-603", denialRationaleType: "step_therapy", denialTextSnippet: "Osimertinib covered as first-line only with documented contraindication or intolerance to first-generation TKI", conflictType: "C", conflictDescription: "Humana requires prior failure of first-generation TKI. NCCN Category 1 consensus designates osimertinib as the preferred first-line; requiring prior inferior TKI directly contradicts the guideline-recommended treatment sequence.", cmsBehaviorFlags: '{"prior_auth_flag":true}', legalExposureTags: '["step therapy contradicts NCCN Cat 1","inferior prior therapy forced","systematic EGFR-NSCLC barrier"]', severity: "high", lastValidatedTimestamp: today },
    { groundTruthRowId: "GT-AETNA-ALECENSA-1L-LUNG", drugId: "alecensa", cancerType: "lung_nsclc", indication: "ALK-positive NSCLC", biomarkerProfile: '{"ALK":"positive"}', lineOfTherapy: "1L", nccnId: "NCCN-LUNG-1L-ALK", nccnCategory: "1", payerId: "Aetna", policyId: "CPB-0910", denialRationaleType: "step_therapy", denialTextSnippet: "Alectinib for ALK-positive NSCLC: covered as second-line after crizotinib failure.", conflictType: "C", conflictDescription: "Aetna requires prior crizotinib for first-line alectinib. NCCN Category 1 and ALEX trial data establish alectinib superiority over crizotinib. Requiring inferior first-line therapy violates NCCN preferred sequence.", cmsBehaviorFlags: '{"prior_auth_flag":true}', legalExposureTags: '["step therapy forces inferior ALK inhibitor","contradicts NCCN Cat 1","ALEX trial OS data"]', severity: "high", lastValidatedTimestamp: today },
    { groundTruthRowId: "GT-CIGNA-TRODELVY-2L-BREAST", drugId: "trodelvy", cancerType: "breast", indication: "Metastatic TNBC", biomarkerProfile: '{"TNBC":"positive","Trop2":"expressed"}', lineOfTherapy: "2L", nccnId: "NCCN-BREAST-2L-TNBC", nccnCategory: "1", payerId: "Cigna", policyId: "CPG-ONC-0887", denialRationaleType: "step_therapy", denialTextSnippet: "Not medically necessary unless >=2 prior lines including checkpoint inhibitor for PD-L1+ disease", conflictType: "C", conflictDescription: "Cigna requires prior checkpoint inhibitor for PD-L1+ TNBC. NCCN Category 1 covers sacituzumab govitecan at 2L without this restriction.", cmsBehaviorFlags: '{"prior_auth_flag":true}', legalExposureTags: '["step therapy contradicts NCCN Cat 1","forces additional prior therapy","TNBC treatment delay"]', severity: "high", lastValidatedTimestamp: today },
    { groundTruthRowId: "GT-AETNA-VERZENIO-1L-BREAST", drugId: "verzenio", cancerType: "breast", indication: "HR+/HER2- early breast cancer", biomarkerProfile: '{"HR":"positive","HER2":"negative","Ki67":"high"}', lineOfTherapy: "1L", nccnId: "NCCN-BREAST-1L-HR-HER2NEG", nccnCategory: "1", payerId: "Aetna", policyId: "CPB-0600", denialRationaleType: "not_medically_necessary", denialTextSnippet: "Not medically necessary for node-negative low-risk disease", conflictType: "B", conflictDescription: "Aetna NMN denial for abemaciclib in HR+/HER2- breast cancer contradicts NCCN Category 1 recommendation for high-risk early breast cancer.", cmsBehaviorFlags: '{"prior_auth_flag":true}', legalExposureTags: '["NMN contradicts NCCN Cat 1","FDA approved indication","high-risk early breast cancer"]', severity: "medium", lastValidatedTimestamp: today },
    { groundTruthRowId: "GT-CIGNA-KEYTRUDA-1L-LUNG", drugId: "keytruda-nsclc", cancerType: "lung_nsclc", indication: "PD-L1 1-49% NSCLC", biomarkerProfile: '{"PDL1":"1-49%","EGFR":"negative","ALK":"negative"}', lineOfTherapy: "1L", nccnId: "NCCN-LUNG-1L-PDL1", nccnCategory: "1", payerId: "Cigna", policyId: "CPG-ONC-3315", denialRationaleType: "not_medically_necessary", denialTextSnippet: "Monotherapy not covered for PD-L1 1-49%; combination required", conflictType: "B", conflictDescription: "Cigna restricts pembrolizumab monotherapy to PD-L1 >=50%. NCCN Category 1 supports pembrolizumab for PD-L1 >=1% in appropriate patients.", cmsBehaviorFlags: '{"prior_auth_flag":true}', legalExposureTags: '["NMN contradicts NCCN Cat 1","FDA approved for PD-L1 >=1%","forces combination therapy"]', severity: "medium", lastValidatedTimestamp: today },
    // Rheumatology GT rows
    { groundTruthRowId: "GT-UHC-ADALIMUMAB-2L-RA", drugId: "adalimumab", cancerType: "rheumatology", indication: "Moderate-to-severe RA after methotrexate failure", biomarkerProfile: '{"RF":"positive","anti_CCP":"positive"}', lineOfTherapy: "2L", nccnId: "ACR-RA-2L-BIOLOGIC", nccnCategory: "1", payerId: "UHC", policyId: "MP-RHEUM-1101", denialRationaleType: "step_therapy", denialTextSnippet: "Not medically necessary without documented failure of 2 conventional DMARDs", conflictType: "C", conflictDescription: "UHC requires 2 conventional DMARD failures before biologic. ACR Category A recommends biologic after single DMARD failure in moderate-to-severe RA with poor prognostic factors.", cmsBehaviorFlags: '{"prior_auth_flag":true}', legalExposureTags: '["step therapy contradicts ACR Cat A","forces additional DMARD failure","RA disease progression risk"]', severity: "high", lastValidatedTimestamp: today },
    { groundTruthRowId: "GT-CIGNA-UPADACITINIB-2L-RA", drugId: "upadacitinib", cancerType: "rheumatology", indication: "Moderate-to-severe RA after biologic failure", biomarkerProfile: '{"JAK":"inhibitor_target"}', lineOfTherapy: "2L", nccnId: "ACR-RA-2L-JAK", nccnCategory: "1", payerId: "Cigna", policyId: "CPG-RHEUM-0445", denialRationaleType: "step_therapy", denialTextSnippet: "Not medically necessary without prior TNF inhibitor failure due to cardiovascular risk profile of JAK inhibitors", conflictType: "C", conflictDescription: "Cigna requires prior TNF inhibitor failure before JAK inhibitor. ACR Category A supports JAK inhibitors as equivalent alternative to biologics after conventional DMARD failure.", cmsBehaviorFlags: '{"prior_auth_flag":true}', legalExposureTags: '["step therapy contradicts ACR Cat A","forces TNF inhibitor trial","SELECT-COMPARE trial data ignored"]', severity: "high", lastValidatedTimestamp: today },
    // Neurology GT rows
    { groundTruthRowId: "GT-UHC-OCRELIZUMAB-1L-MS", drugId: "ocrelizumab", cancerType: "neurology", indication: "Relapsing or primary progressive MS", biomarkerProfile: '{"MS_type":"RRMS or PPMS"}', lineOfTherapy: "1L", nccnId: "AAN-MS-1L-ANTI-CD20", nccnCategory: "1", payerId: "UHC", policyId: "MP-NEURO-2201", denialRationaleType: "step_therapy", denialTextSnippet: "Not medically necessary as first-line without prior platform therapy failure", conflictType: "C", conflictDescription: "UHC requires prior interferon beta or glatiramer acetate failure before ocrelizumab. AAN Level A supports ocrelizumab as first-line high-efficacy therapy, especially for PPMS where no step therapy requirement exists.", cmsBehaviorFlags: '{"prior_auth_flag":true}', legalExposureTags: '["step therapy contradicts AAN Level A","PPMS has no step therapy alternative","ORATORIO trial data"]', severity: "high", lastValidatedTimestamp: today },
    { groundTruthRowId: "GT-AETNA-NATALIZUMAB-2L-MS", drugId: "natalizumab", cancerType: "neurology", indication: "Highly active relapsing MS", biomarkerProfile: '{"MS_type":"RRMS","JCV_antibody":"negative"}', lineOfTherapy: "2L", nccnId: "AAN-MS-2L-NATALIZUMAB", nccnCategory: "1", payerId: "Aetna", policyId: "CPB-NEURO-0330", denialRationaleType: "step_therapy", denialTextSnippet: "Not medically necessary without prior failure of 2 platform therapies", conflictType: "C", conflictDescription: "Aetna requires 2 platform therapy failures before natalizumab. AAN Level A supports natalizumab for highly active RRMS after single therapy failure when disease activity is high.", cmsBehaviorFlags: '{"prior_auth_flag":true}', legalExposureTags: '["step therapy contradicts AAN Level A","highly active MS requires rapid escalation","AFFIRM trial data"]', severity: "high", lastValidatedTimestamp: today },
  ];

  gtRows.forEach(row => storage.upsertGroundTruth(row));

  // ─── PATIENTS ─────────────────────────────────────────────────────────────────
  const patients = [
    { organizationId: DEMO_ORG_ID, patientId: "PT-2026-001", cancerType: "breast", stage: "Stage IV", biomarkers: JSON.stringify({ HER2: "low (IHC 1+)", HR: "positive", ESR1: "wildtype" }), priorTherapies: JSON.stringify([{ drug: "anastrozole", start: "2024-01", end: "2024-08", response: "progression" }, { drug: "fulvestrant", start: "2024-09", end: "2025-01", response: "progression" }]), performanceStatus: "ECOG 1", clinicName: "MD Anderson Breast Center", state: "TX" },
    { organizationId: DEMO_ORG_ID, patientId: "PT-2026-002", cancerType: "lung_nsclc", stage: "Stage IV", biomarkers: JSON.stringify({ EGFR: "L858R", PDL1: "40%", ALK: "negative" }), priorTherapies: JSON.stringify([]), performanceStatus: "ECOG 1", clinicName: "MD Anderson Thoracic Oncology", state: "TX" },
    { organizationId: DEMO_ORG_ID, patientId: "PT-2026-003", cancerType: "glioblastoma", stage: "Grade 4 GBM", biomarkers: JSON.stringify({ IDH: "wildtype", MGMT: "unmethylated", EGFR: "amplified" }), priorTherapies: JSON.stringify([{ drug: "temozolomide", start: "2025-03", end: "2025-06", response: "completion" }]), performanceStatus: "ECOG 1", clinicName: "MD Anderson Neuro-Oncology", state: "TX" },
    { organizationId: DEMO_ORG_ID, patientId: "PT-2026-004", cancerType: "prostate", stage: "Stage IV mCRPC", biomarkers: JSON.stringify({ AR: "positive", PSA: "45.2", CRPC: "yes" }), priorTherapies: JSON.stringify([{ drug: "leuprolide", start: "2023-06", end: "2024-12", response: "castration-resistant" }]), performanceStatus: "ECOG 1", clinicName: "MD Anderson GU Oncology", state: "TX" },
    { organizationId: DEMO_ORG_ID, patientId: "PT-2026-005", cancerType: "leukemia_aml", stage: "Relapsed/Refractory AML", biomarkers: JSON.stringify({ FLT3: "ITD positive", IDH2: "wildtype", NPM1: "mutated" }), priorTherapies: JSON.stringify([{ drug: "cytarabine + daunorubicin", start: "2024-08", end: "2024-10", response: "partial response" }]), performanceStatus: "ECOG 2", clinicName: "MD Anderson Leukemia", state: "TX" },
    { organizationId: DEMO_ORG_ID, patientId: "PT-2026-006", cancerType: "myeloma", stage: "Stage III Multiple Myeloma", biomarkers: JSON.stringify({ FISH: "del17p", ISS: "III", LDH: "elevated" }), priorTherapies: JSON.stringify([{ drug: "bortezomib + lenalidomide + dexamethasone", start: "2024-02", end: "2024-08", response: "VGPR" }]), performanceStatus: "ECOG 1", clinicName: "MD Anderson Myeloma", state: "TX" },
    { organizationId: DEMO_ORG_ID, patientId: "PT-2026-007", cancerType: "bladder", stage: "Stage IV Urothelial", biomarkers: JSON.stringify({ PDL1: "high", FGFR3: "mutated", HER2: "negative" }), priorTherapies: JSON.stringify([{ drug: "cisplatin + gemcitabine", start: "2024-11", end: "2025-02", response: "progression" }]), performanceStatus: "ECOG 1", clinicName: "MD Anderson GU Oncology", state: "TX" },
    { organizationId: DEMO_ORG_ID, patientId: "PT-2026-008", cancerType: "cervical", stage: "Stage IVB Cervical", biomarkers: JSON.stringify({ PDL1: "positive", HPV: "16/18 positive", MSI: "stable" }), priorTherapies: JSON.stringify([{ drug: "cisplatin + paclitaxel + bevacizumab", start: "2025-01", end: "2025-04", response: "progression" }]), performanceStatus: "ECOG 1", clinicName: "MD Anderson GYN Oncology", state: "TX" },
  ];

  patients.forEach(p => storage.insertPatient(p));

  // ─── DENIALS ─────────────────────────────────────────────────────────────────
  const denials = [
    { organizationId: DEMO_ORG_ID, denialRecordId: "DN-2026-001", patientId: "PT-2026-001", payerId: "UHC", payerName: "UnitedHealthcare", payerFaxNumber: PAYER_FAX_NUMBERS["UHC"], memberId: "UHC-ENC-001", drugId: "enhertu", drugNameRaw: "Enhertu (trastuzumab deruxtecan)", icd10Codes: "C50.912,Z17.0", denialReasonCode: "not_medically_necessary", denialReasonText: "Requested therapy Enhertu (trastuzumab deruxtecan) does not meet medical necessity criteria for the submitted diagnosis. HER2-low breast cancer (IHC 1+) does not qualify under current coverage policy MP-ONC-1234. Coverage is limited to HER2-positive (IHC 3+ or ISH+) disease. Request denied.", denialDate: "2026-03-10", referenceNumber: "PA-2026-4491827", rawDocumentText: "PRIOR AUTHORIZATION DENIAL NOTICE\nUnitedHealthcare\nDate: March 10, 2026\nMember: [REDACTED]\nDrug: Enhertu (trastuzumab deruxtecan)\nDecision: DENIED\nReason: Not Medically Necessary\n\nRequested therapy does not meet medical necessity criteria for the submitted diagnosis. HER2-low breast cancer (IHC 1+) does not qualify under current coverage policy MP-ONC-1234." },
    { organizationId: DEMO_ORG_ID, denialRecordId: "DN-2026-002", patientId: "PT-2026-002", payerId: "UHC", payerName: "UnitedHealthcare", payerFaxNumber: PAYER_FAX_NUMBERS["UHC"], memberId: "UHC-OSI-002", drugId: "tagrisso", drugNameRaw: "Tagrisso (osimertinib)", icd10Codes: "C34.12,C78.00", denialReasonCode: "step_therapy", denialReasonText: "Step therapy requirement not met. Tagrisso (osimertinib) is not covered as first-line therapy unless the member has trialed and failed a first-generation EGFR TKI (erlotinib or gefitinib) or has documented T790M mutation at diagnosis.", denialDate: "2026-03-11", referenceNumber: "PA-2026-5582910", rawDocumentText: "PRIOR AUTHORIZATION DENIAL\nDate: March 11, 2026\nDrug: Tagrisso (osimertinib)\nDecision: DENIED - Step Therapy Not Met\n\nTagrisso is not covered as first-line therapy without prior first-generation EGFR TKI trial." },
    { organizationId: DEMO_ORG_ID, denialRecordId: "DN-2026-003", patientId: "PT-2026-003", payerId: "UHC", payerName: "UnitedHealthcare", payerFaxNumber: PAYER_FAX_NUMBERS["UHC"], memberId: "UHC-OPT-003", drugId: "optune", drugNameRaw: "Optune (tumor treating fields)", icd10Codes: "C71.9", denialReasonCode: "experimental", denialReasonText: "Optune (tumor treating fields) is classified as experimental and investigational under UHC Medical Policy. This technology has not been shown to meet the UHC coverage criteria for proven benefit in standard clinical practice.", denialDate: "2026-03-12", referenceNumber: "PA-2026-6693044", rawDocumentText: "PRIOR AUTHORIZATION DENIAL\nDate: March 12, 2026\nDrug: Optune (tumor treating fields device)\nDecision: DENIED - Experimental/Investigational\n\nOptune is classified as experimental and investigational under UHC Medical Policy MP-ONC-2891." },
    { organizationId: DEMO_ORG_ID, denialRecordId: "DN-2026-004", patientId: "PT-2026-004", payerId: "UHC", payerName: "UnitedHealthcare", payerFaxNumber: PAYER_FAX_NUMBERS["UHC"], memberId: "UHC-ENZ-004", drugId: "enzalutamide", drugNameRaw: "Xtandi (enzalutamide)", icd10Codes: "C61,C79.51", denialReasonCode: "step_therapy", denialReasonText: "Xtandi (enzalutamide) requires prior failure of abiraterone acetate (Zytiga) for metastatic CRPC. Please provide documentation of prior abiraterone trial.", denialDate: "2026-03-13", referenceNumber: "PA-2026-7704155", rawDocumentText: "PRIOR AUTHORIZATION DENIAL\nDate: March 13, 2026\nDrug: Xtandi (enzalutamide)\nDecision: DENIED - Step Therapy Not Met\n\nRequires prior abiraterone failure for mCRPC." },
    { organizationId: DEMO_ORG_ID, denialRecordId: "DN-2026-005", patientId: "PT-2026-005", payerId: "UHC", payerName: "UnitedHealthcare", payerFaxNumber: PAYER_FAX_NUMBERS["UHC"], memberId: "UHC-AML-005", drugId: null, drugNameRaw: "Midostaurin (Rydapt)", icd10Codes: "C91.00", denialReasonCode: "not_medically_necessary", denialReasonText: "Midostaurin (Rydapt) is not medically necessary for the submitted diagnosis. FLT3 mutation testing documentation required. Coverage denied pending additional clinical documentation.", denialDate: "2026-03-14", referenceNumber: "PA-2026-8815266", rawDocumentText: "PRIOR AUTHORIZATION DENIAL\nDate: March 14, 2026\nDrug: Midostaurin (Rydapt)\nDecision: DENIED - Not Medically Necessary\n\nFLT3 mutation documentation required." },
    { organizationId: DEMO_ORG_ID, denialRecordId: "DN-2026-006", patientId: "PT-2026-006", payerId: "UHC", payerName: "UnitedHealthcare", payerFaxNumber: PAYER_FAX_NUMBERS["UHC"], memberId: "UHC-MYL-006", drugId: null, drugNameRaw: "Daratumumab (Darzalex)", icd10Codes: "C90.00", denialReasonCode: "step_therapy", denialReasonText: "Daratumumab (Darzalex) requires prior failure of at least 3 prior lines of therapy including a proteasome inhibitor and an immunomodulatory agent.", denialDate: "2026-03-15", referenceNumber: "PA-2026-9926377", rawDocumentText: "PRIOR AUTHORIZATION DENIAL\nDate: March 15, 2026\nDrug: Daratumumab (Darzalex)\nDecision: DENIED - Step Therapy Not Met\n\nRequires 3 prior lines including PI and IMiD." },
    { organizationId: DEMO_ORG_ID, denialRecordId: "DN-2026-007", patientId: "PT-2026-007", payerId: "Aetna", payerName: "Aetna", payerFaxNumber: PAYER_FAX_NUMBERS["Aetna"], memberId: "AET-BLD-007", drugId: "keytruda-nsclc", drugNameRaw: "Keytruda (pembrolizumab)", icd10Codes: "C67.9,C77.1", denialReasonCode: "not_medically_necessary", denialReasonText: "Pembrolizumab (Keytruda) is not medically necessary for bladder cancer without prior platinum-based chemotherapy failure. Step therapy with cisplatin-gemcitabine required.", denialDate: "2026-03-16", referenceNumber: "PA-2026-1037488", rawDocumentText: "PRIOR AUTHORIZATION DENIAL\nDate: March 16, 2026\nDrug: Keytruda (pembrolizumab)\nDecision: DENIED - Not Medically Necessary\n\nPrior platinum-based chemotherapy required for bladder cancer." },
    { organizationId: DEMO_ORG_ID, denialRecordId: "DN-2026-008", patientId: "PT-2026-008", payerId: "Humana", payerName: "Humana", payerFaxNumber: PAYER_FAX_NUMBERS["Humana"], memberId: "HUM-CRV-008", drugId: "keytruda-nsclc", drugNameRaw: "Keytruda (pembrolizumab) + Chemotherapy", icd10Codes: "C53.9,C77.5", denialReasonCode: "experimental", denialReasonText: "Pembrolizumab combination therapy for cervical cancer is classified as experimental under Humana policy. Insufficient evidence for this indication beyond single-agent use.", denialDate: "2026-03-17", referenceNumber: "PA-2026-1148599", rawDocumentText: "PRIOR AUTHORIZATION DENIAL\nDate: March 17, 2026\nDrug: Keytruda + Chemotherapy\nDecision: DENIED - Experimental\n\nCombination pembrolizumab for cervical cancer classified as experimental." },
  ];

  denials.forEach(d => storage.insertDenial(d));

  const result = {
    status: "seeded",
    drugs: storage.getAllDrugs().length,
    nccn: storage.getAllNccn().length,
    policies: storage.getAllPayerPolicies().length,
    groundTruth: storage.getAllGroundTruth().length,
    patients: storage.getAllPatients(DEMO_ORG_ID).length,
    denials: storage.getAllDenials(DEMO_ORG_ID).length,
  };
  console.log("[Seed] Complete:", JSON.stringify(result));
  return result;
}
